 jobs:
  build: 
    docker: 
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1.101-bionic

    steps:
      - checkout
      - run: dotnet build
      - store_artifacts:
          path: orm-2.7.0/bin/Debug/netstandard2.0/doctrine.dll
